In [2]:
import numpy as np
from sklearn import naive_bayes as nb

In [3]:
dataset = [[['sunny','high_humidity'],'No'],
          [['overcast','low_humidity'],'Yes'],
          [['rainy','low_humidity'],'yes'],
          [['sunny','med_humidity'],'Yes'],
          [['sunny','low_humidity'],'Yes'],
          [['overcast','med_humidity'],'Yes'],
          [['rainy','high_humidity'],'No'],
          [['rainy','high_humidity'],'No'],
          [['sunny','med_humidity'],'Yes'],
          [['rainy','low_humidity'],'Yes'],
          [['sunny','high_humidity'],'No'],
          [['overcast','med_humidity'],'Yes'],
          [['overcast','low_humidity'],'Yes'],
          [['rainy','high_humidity'],'No']]

In [4]:
dataset_array = np.asarray(dataset)

In [5]:
np.shape(dataset_array[0][0])

(2,)

In [6]:
print(dataset_array[0][0][0] , dataset_array[0][0][1])
print(dataset_array[:,0])

sunny high_humidity
[list(['sunny', 'high_humidity']) list(['overcast', 'low_humidity'])
 list(['rainy', 'low_humidity']) list(['sunny', 'med_humidity'])
 list(['sunny', 'low_humidity']) list(['overcast', 'med_humidity'])
 list(['rainy', 'high_humidity']) list(['rainy', 'high_humidity'])
 list(['sunny', 'med_humidity']) list(['rainy', 'low_humidity'])
 list(['sunny', 'high_humidity']) list(['overcast', 'med_humidity'])
 list(['overcast', 'low_humidity']) list(['rainy', 'high_humidity'])]


In [7]:
def factorization(lst):
    a = b =0
    if lst[0] == 'sunny':
        a = 0
    elif lst[0] == 'rainy':
        a = 1
    else:
        a = 2
    if lst[1] == 'low_humidity':
        b = 0
    elif lst[1] == 'med_humidity':
        b = 1
    else:
        b = 2
    return a,b

In [8]:
factorized_feature_list = []
for feature_list in dataset_array[:,0]:
    factorized_feature_list.append(factorization(feature_list))
factorized_feature_array = np.asarray(factorized_feature_list)

In [9]:
factorized_label_list = []
for output_label in dataset_array[:,1]:
    if output_label == 'Yes':
        factorized_label_list.append(1)
    else:
        factorized_label_list.append(0)
factorized_label_array = np.asarray(factorized_label_list)

In [10]:
print(str(factorized_feature_array.shape)+"\n" +str(factorized_label_array.shape))

(14, 2)
(14,)


In [11]:
gaussian_model = nb.GaussianNB()
gaussian_model.fit(factorized_feature_array,factorized_label_array)

GaussianNB(priors=None)

In [12]:
gaussian_model.predict([(1,2)])

array([0])

In [13]:
gaussian_model.predict([(2,2)])

array([0])

In [17]:
gaussian_model.predict_proba([(0,1)])

array([[0.45653287, 0.54346713]])

In [15]:
gaussian_model.predict_proba([(2,1)])

array([[0.03031826, 0.96968174]])