In [1]:
import numpy as np
from sklearn import naive_bayes as nb
import pandas as pd
from modules.factorization import factorization

In [2]:
dataset = [[['sunny'],'No'],
          [['overcast'],'Yes'],
          [['rainy'],'yes'],
          [['sunny'],'Yes'],
          [['sunny'],'Yes'],
          [['overcast'],'Yes'],
          [['rainy'],'No'],
          [['rainy'],'No'],
          [['sunny'],'Yes'],
          [['rainy'],'Yes'],
          [['sunny'],'No'],
          [['overcast'],'Yes'],
          [['overcast'],'Yes'],
          [['rainy'],'No']]

In [3]:
dataset_array = np.asarray(dataset)

In [4]:
#could use this to factorise our data in pandas only
weather_forecast = ['sunny','rainy','overcast']
play = ['No','Yes']

In [4]:
dataset_array[:,0]

array([list(['sunny']), list(['overcast']), list(['rainy']),
       list(['sunny']), list(['sunny']), list(['overcast']),
       list(['rainy']), list(['rainy']), list(['sunny']), list(['rainy']),
       list(['sunny']), list(['overcast']), list(['overcast']),
       list(['rainy'])], dtype=object)

In [5]:
factorised_dataset_feature_list = []
for a_list in dataset_array[:,0]:
    if a_list[0] == 'sunny':
        factorised_dataset_feature_list.append(0)
    if a_list[0] == 'rainy':
        factorised_dataset_feature_list.append(1)
    if a_list[0] == 'overcast':
        factorised_dataset_feature_list.append(2)
factorised_dataset_feature_array =np.asarray(factorised_dataset_feature_list)
print(factorised_dataset_feature_array)

[0 2 1 0 0 2 1 1 0 1 0 2 2 1]


In [8]:
factorised_dataset_feature_array
#print(np.shape(factorised_dataset_feature_array))
factorised_dataset_feature_array=np.reshape(factorised_dataset_feature_array,(-1,1))
print(factorised_dataset_feature_array.shape)

(14, 1)


In [9]:
factorised_dataset_label_list = []
for a_label in dataset_array[:,1]:
    if a_label == 'Yes':
        factorised_dataset_label_list.append(1)
    else:
        factorised_dataset_label_list.append(0)
factorised_dataset_label_array = np.asarray(factorised_dataset_label_list)

In [10]:
factorised_dataset_label_array

array([0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0])

In [11]:
gaussian_model = nb.GaussianNB()

In [12]:
gaussian_model.fit(factorised_dataset_feature_array,factorised_dataset_label_array)

GaussianNB(priors=None)

In [12]:
gaussian_model.predict_proba(0)

array([[0.53119576, 0.46880424]])

In [13]:
gaussian_model.predict_proba(1)

array([[0.5368512, 0.4631488]])

In [13]:
gaussian_model.predict_proba(2)

array([[0.04046685, 0.95953315]])

<h3>Using a general Factorization function
